const state = { user: null, catalogs: null };
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

async function api(url, options) {
  const response = await fetch(url, { headers: { 'Content-Type': 'application/json', ...(state.user ? { 'X-User-Id': state.user.id } : {}) }, ...options });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Não foi possível concluir a operação.');
  return data;
}
function showNotice(message, error = false) { const notice = $('#notice'); notice.textContent = message; notice.className = `notice${error ? ' error' : ''}`; setTimeout(() => notice.classList.add('hidden'), 4500); }
function fillSelects() { const locationOptions = state.catalogs.locations.map((item) => `<option value="${item.id}">${item.name}</option>`).join(''); const typeOptions = state.catalogs.occurrenceTypes.map((item) => `<option value="${item.id}">${item.name}</option>`).join(''); $$('.location-select, #location').forEach((select) => select.insertAdjacentHTML('beforeend', locationOptions)); $$('.type-select, #occurrence-type').forEach((select) => select.insertAdjacentHTML('beforeend', typeOptions)); }
function formValues(form) { return Object.fromEntries(new FormData(form).entries()); }
function loadLoginUsers(users) {
  $('#login-user').innerHTML = users.filter((user) => user.active).map((user) => `<option value="${user.id}">${user.name} · ${user.profile}</option>`).join('');
}
function renderUsers(users) {
  $('#users-list').innerHTML = users.map((user) => `<tr><td><b>${user.name}</b></td><td>${user.email}</td><td>${user.profile}</td><td><span class="user-status ${user.active ? 'active' : 'inactive'}">${user.active ? 'Ativo' : 'Desativado'}</span></td><td><div class="actions"><button data-user-action="edit" data-id="${user.id}">Editar</button>${user.active && user.id !== state.user.id ? `<button data-user-action="delete" data-id="${user.id}">Excluir</button>` : ''}</div></td></tr>`).join('');
  $('#empty-users').classList.toggle('hidden', users.length > 0);
}
async function loadUsers() { const users = await api('/api/users'); renderUsers(users); loadLoginUsers(users); }
function resetUserForm() { $('#user-form').reset(); $('#user-form [name="id"]').value = ''; $('#user-password').required = true; $('#user-password').placeholder = 'Digite 4 números'; $('#user-submit-label').textContent = 'Cadastrar usuário'; $('#cancel-user-edit').classList.add('hidden'); }
function updateCredentialNumber() {
  const type = $('#credential-type');
  const field = $('#credential-number-field');
  const number = $('#credential-number');
  const shouldShow = Boolean(type.value) && type.value !== 'nao_possui';
  field.classList.toggle('is-hidden', !shouldShow);
  number.disabled = !shouldShow;
  number.required = shouldShow;
  if (!shouldShow) number.value = '';
}
async function loadApprovals() { const occurrences = await api('/api/occurrences'); const pending = occurrences.filter((item) => ['rascunho', 'em_analise'].includes(item.status)); const canDecide = ['Supervisor', 'Coordenador', 'Gerente', 'NTI'].includes(state.user?.profile); $('#pending-count').textContent = pending.length; $('#occurrence-list').innerHTML = occurrences.map((item) => `<tr><td><b>${item.protocol}</b><br><small>${new Date(item.occurred_at).toLocaleString('pt-BR')}</small></td><td>${item.occurrence_type}<br><small>${item.frequentador_name || 'Frequentador não informado'}</small></td><td>${item.location}</td><td>${item.reported_by_name}</td><td><span class="badge ${item.status}">${item.status.replace('_', ' ')}</span></td><td>${pending.includes(item) && canDecide ? `<div class="actions"><button data-action="approve" data-id="${item.id}">Aprovar</button><button data-action="reject" data-id="${item.id}">Reprovar</button><button data-action="request_correction" data-id="${item.id}">Correção</button></div>` : '<small>Consulta</small>'}</td></tr>`).join(''); $('#empty-list').classList.toggle('hidden', occurrences.length > 0); }
function activateView(id) { $$('.view').forEach((view) => view.classList.toggle('hidden', view.id !== id)); $$('.nav-button').forEach((button) => button.classList.toggle('active', button.dataset.view === id)); $('#page-title').textContent = id === 'medical-view' ? 'Incidente médico' : id === 'approval-view' ? 'Fila de aprovação' : id === 'users-view' ? 'Gestão de usuários' : 'Nova ocorrência'; if (id === 'approval-view') loadApprovals().catch((error) => showNotice(error.message, true)); if (id === 'users-view') loadUsers().catch((error) => showNotice(error.message, true)); }
async function enter(user) { state.user = user; $('#login-screen').classList.add('hidden'); $('#app').classList.remove('hidden'); $('#current-user').textContent = `${user.name} · ${user.profile}`; $('#greeting').textContent = user.name.split(' ')[0]; $$('.nti-only').forEach((element) => element.classList.toggle('hidden', user.profile !== 'NTI')); state.catalogs = await api('/api/occurrences/catalogs'); fillSelects(); $('#today').textContent = new Date().toLocaleDateString('pt-BR', { dateStyle: 'long' }); loadApprovals(); if (user.profile === 'NTI') loadUsers(); }

$('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const user = await api('/api/auth/login', { method: 'POST', body: JSON.stringify({ userId: Number($('#login-user').value), password: $('#login-password').value }) }); await enter(user); $('#login-password').value = ''; } catch (error) { showNotice(error.message, true); } });
$('#logout').addEventListener('click', () => { state.user = null; $('#app').classList.add('hidden'); $('#login-screen').classList.remove('hidden'); });
$$('.nav-button').forEach((button) => button.addEventListener('click', () => activateView(button.dataset.view)));
$('#refresh').addEventListener('click', () => loadApprovals().catch((error) => showNotice(error.message, true)));
$('#credential-type').addEventListener('change', updateCredentialNumber);
$('#occurrence-form').addEventListener('reset', () => setTimeout(updateCredentialNumber));
$('#occurrence-form').addEventListener('submit', async (event) => { event.preventDefault(); const values = formValues(event.target); try { await api('/api/occurrences', { method: 'POST', body: JSON.stringify({ occurrenceTypeId: values.occurrenceTypeId, locationId: values.locationId, reportedBy: state.user.id, occurredAt: `${values.date}T${values.time}`, confidentiality: values.confidentiality, description: values.description, sescGuidance: values.guidance, referredToManagement: Boolean(values.management), frequentador: { name: values.frequentadorName, document: values.document, phone: values.phone, credentialType: values.credentialType, credentialNumber: values.credentialNumber, birthDate: values.birthDate }, acompanhante: { name: values.companionName, relationship: values.relationship } }) }); event.target.reset(); updateCredentialNumber(); showNotice('Ocorrência salva com sucesso.'); loadApprovals(); } catch (error) { showNotice(error.message, true); } });
$('#medical-form').addEventListener('submit', async (event) => { event.preventDefault(); const values = formValues(event.target); try { await api('/api/occurrences', { method: 'POST', body: JSON.stringify({ occurrenceTypeId: values.occurrenceTypeId, locationId: values.locationId, reportedBy: state.user.id, occurredAt: `${values.date}T${values.time}`, description: values.complaint || 'Incidente médico', frequentador: { name: values.frequentadorName }, medicalIncident: { professional: values.professional, registration: values.registration, complaint: values.complaint, hda: values.hda, physicalExam: values.physicalExam, conduct: values.conduct, outcome: values.outcome, referralLocation: values.referralLocation } }) }); event.target.reset(); showNotice('Incidente médico salvo com sucesso.'); loadApprovals(); } catch (error) { showNotice(error.message, true); } });
$('#occurrence-list').addEventListener('click', async (event) => { const button = event.target.closest('[data-action]'); if (!button) return; const details = window.prompt(button.dataset.action === 'request_correction' ? 'Informe o que deve ser corrigido:' : 'Parecer da análise:') || ''; const measuresTaken = window.prompt('Medidas adotadas (opcional):') || ''; try { await api(`/api/occurrences/${button.dataset.id}/decision`, { method: 'PATCH', body: JSON.stringify({ action: button.dataset.action, userId: state.user.id, details, reviewerComment: details, measuresTaken }) }); showNotice('Fluxo atualizado e registrado na auditoria.'); loadApprovals(); } catch (error) { showNotice(error.message, true); } });
api('/api/users').then(loadLoginUsers).catch((error) => { $('#login-user').innerHTML = `<option>${error.message}</option>`; });
$('#change-password').addEventListener('click', () => { $('#password-dialog').showModal(); });
$('#close-password').addEventListener('click', () => { $('#password-dialog').close(); });
$('#password-form').addEventListener('submit', async (event) => { event.preventDefault(); const values = formValues(event.target); try { await api('/api/auth/password', { method: 'PATCH', body: JSON.stringify(values) }); $('#password-dialog').close(); event.target.reset(); showNotice('Senha alterada com sucesso.'); } catch (error) { showNotice(error.message, true); } });
$('#user-form').addEventListener('submit', async (event) => { event.preventDefault(); const values = formValues(event.target); const passwordIsValid = /^\d{4}$/.test(values.password || ''); if ((!values.id && !passwordIsValid) || (values.id && values.password && !passwordIsValid)) { showNotice('A senha deve conter exatamente 4 dígitos numéricos.', true); $('#user-password').focus(); return; } try { const method = values.id ? 'PATCH' : 'POST'; const url = values.id ? `/api/users/${values.id}` : '/api/users'; const payload = { name: values.name, email: values.email, profile: values.profile }; if (values.password) payload.password = values.password; await api(url, { method, body: JSON.stringify(payload) }); resetUserForm(); await loadUsers(); showNotice(values.id ? 'Usuário atualizado com sucesso.' : 'Usuário cadastrado com sucesso.'); } catch (error) { showNotice(error.message, true); } });
$('#cancel-user-edit').addEventListener('click', resetUserForm);
$('#users-list').addEventListener('click', async (event) => { const button = event.target.closest('[data-user-action]'); if (!button) return; const users = await api('/api/users'); const user = users.find((item) => item.id === Number(button.dataset.id)); if (!user) return; if (button.dataset.userAction === 'edit') { $('#user-form [name="id"]').value = user.id; $('#user-form [name="name"]').value = user.name; $('#user-form [name="email"]').value = user.email; $('#user-form [name="profile"]').value = user.profile; $('#user-password').value = ''; $('#user-password').required = false; $('#user-password').placeholder = 'Deixe vazio para manter'; $('#user-submit-label').textContent = 'Salvar alterações'; $('#cancel-user-edit').classList.remove('hidden'); $('#user-form').scrollIntoView({ behavior: 'smooth', block: 'center' }); return; } if (window.confirm(`Desativar o usuário ${user.name}?`)) { try { await api(`/api/users/${user.id}`, { method: 'DELETE' }); await loadUsers(); showNotice('Usuário desativado e removido do acesso.'); } catch (error) { showNotice(error.message, true); } } });
